### ISSUE TITLE
[MAJOR ISSUE] Now it's 2012 buttons don't work!

### ISSUE THREAD

**Issue by Psithief** [Codisimus/ButtonWarp#1]
`"You cannot use that again for 356 days, 31 hours, 51 minutes, 36 seconds"`
`"You cannot use that again for 361 days, 23 hours, 51 minutes, 36 seconds"`

This happened as soon as it rolled into 2012. There is a MAJOR failure in your code. Please fix.

Edit: I'm going around adding very large maximum use values to each button. This is the only workaround I've found so far.

**Comment by Codisimus** [comment]
fixed*
