### ISSUE TITLE
ButtonWarp sole cause of some major issues and server crashing. 

### ISSUE THREAD

**Issue by ghost** [Codisimus/ButtonWarp#2]
Over the past few weeks, I have been experiencing a server crash just about every day. It took a few days to sort out what was causing my server to crash, but I have finally narrowed the issue down to ButtonWarp with the help of mbaxter. So, I hope you can fix the issue(s) with ease.

Spigot #397 http://ci.md-5.net/job/Spigot/397/
ButtonWarp v2.1.2 http://dev.bukkit.org/server-mods/buttonwarp/files/39-v2-1-2/

Here are three of many crash logs.
http://pastebin.com/YP4HcNgt
http://pastebin.com/PPjgFW89
http://pastebin.com/ZAg7BDAh

Here are two of many exception traces that occur when a player is kicked to prevent the server from crashing. 
http://pastebin.com/izrsztdS
http://pastebin.com/Bb3b2LJQ

Using mbaxter's custom plugin to log async tasks to narrow down which plugin may be causing the issue, this was found.
http://pastebin.com/QGnELPC6

In the course of about 9 hours, that async task has been logged 5,267 times. 

Here is a log showing that the async task from ButtonWarp occurred at the same time as someone being kicked from the server to prevent it from crashing. 
http://pastebin.com/uqEjsfR3

**Comment by mbax** [comment]
You cannot teleport a player asynchronously. That's your issue.

**Comment by ghost** [comment]
If you wish to pull my code: https://github.com/rtcabooservb/ButtonWarp/commits/master

This fixes the random server crashes and player kicks, as player teleporting should not be async. I have tested my changes and so far, no crashes or player kicks. The plugin also boots up just fine and button warps are functional.

**Comment by Codisimus** [comment]
Not sure how I missed this b4, but I have fixed my foolish mistake by now anyway.

**Comment by ghost** [comment]
I saw, which is why I closed the ticket. Thanks for fixing though.

**Comment by mbax** [comment]
Hurray!
